-- tag
INSERT OR IGNORE INTO tag (name, tag_group, seed_version) VALUES
  ('nervous_system',       'emotion_system',   1),
  ('hormone',              'emotion_system',   1);

-- label: Emotion Layer 1
WITH v(name) AS (VALUES ('Bright'), ('Warm'), ('Still'), ('Heavy'), ('Charged'))
INSERT OR IGNORE INTO label (entry_type_id, name)
SELECT et.id, v.name FROM entry_type et, v WHERE et.name = 'Emotion';

-- label: Emotion Layer 2
WITH v(parent, child) AS (VALUES
  ('Bright',  'Joyful'),
  ('Bright',  'Excited'),
  ('Bright',  'Empowered'),
  ('Bright',  'Inspired'),
  ('Warm',    'Grateful'),
  ('Warm',    'Connected'),
  ('Warm',    'Tender'),
  ('Warm',    'Hopeful'),
  ('Warm',    'Calm'),
  ('Still',   'Curious'),
  ('Still',   'Present'),
  ('Still',   'Flat'),
  ('Heavy',   'Melancholy'),
  ('Heavy',   'Grief'),
  ('Heavy',   'Longing'),
  ('Heavy',   'Numb'),
  ('Heavy',   'Disenchanted'),
  ('Heavy',   'Ashamed'),
  ('Heavy',   'Burned out'),
  ('Charged', 'Anxious'),
  ('Charged', 'Dread'),
  ('Charged', 'Overwhelmed'),
  ('Charged', 'Panicked'),
  ('Charged', 'Disgusted'),
  ('Charged', 'Angry')
)
INSERT OR IGNORE INTO label (entry_type_id, name, parent_id)
SELECT et.id, v.child, pl.id
FROM entry_type et
JOIN v ON 1=1
JOIN label pl ON pl.entry_type_id = et.id AND pl.name = v.parent
WHERE et.name = 'Emotion';

-- label: Emotion Layer 3
WITH v(parent, child) AS (VALUES
  ('Joyful',        'Happy'),
  ('Joyful',        'Delighted'),
  ('Joyful',        'Playful'),
  ('Joyful',        'Giddy'),
  ('Excited',       'Enthusiastic'),
  ('Excited',       'Eager'),
  ('Excited',       'Elated'),
  ('Excited',       'Exhilarated'),
  ('Empowered',     'Confident'),
  ('Empowered',     'Capable'),
  ('Empowered',     'Courageous'),
  ('Empowered',     'Accomplished'),
  ('Empowered',     'Proud'),
  ('Inspired',      'Motivated'),
  ('Inspired',      'Energised'),
  ('Grateful',      'Thankful'),
  ('Grateful',      'Appreciative'),
  ('Grateful',      'Moved'),
  ('Grateful',      'Touched'),
  ('Connected',     'Loved'),
  ('Connected',     'Accepted'),
  ('Connected',     'Valued'),
  ('Connected',     'Safe'),
  ('Connected',     'Cherished'),
  ('Tender',        'Compassionate'),
  ('Tender',        'Affectionate'),
  ('Tender',        'Gentle'),
  ('Hopeful',       'Optimistic'),
  ('Hopeful',       'Encouraged'),
  ('Hopeful',       'Reassured'),
  ('Calm',          'Peaceful'),
  ('Calm',          'Relieved'),
  ('Calm',          'Content'),
  ('Calm',          'Settled'),
  ('Calm',          'At-ease'),
  ('Calm',          'Comfortable'),
  ('Curious',       'Interested'),
  ('Curious',       'Inquisitive'),
  ('Curious',       'Wondering'),
  ('Present',       'Attentive'),
  ('Present',       'Aware'),
  ('Present',       'Centered'),
  ('Present',       'Absorbed'),
  ('Flat',          'Bored'),
  ('Flat',          'Indifferent'),
  ('Flat',          'Meh'),
  ('Flat',          'Disengaged'),
  ('Melancholy',    'Sad'),
  ('Melancholy',    'Hurt'),
  ('Melancholy',    'Blue'),
  ('Melancholy',    'Sorrowful'),
  ('Melancholy',    'Dejected'),
  ('Melancholy',    'Disappointed'),
  ('Grief',         'Heartbroken'),
  ('Grief',         'Devastated'),
  ('Grief',         'Bereft'),
  ('Grief',         'Bereaved'),
  ('Grief',         'Mourning'),
  ('Longing',       'Isolated'),
  ('Longing',       'Disconnected'),
  ('Longing',       'Wistful'),
  ('Longing',       'Nostalgic'),
  ('Longing',       'Lonely'),
  ('Numb',          'Empty'),
  ('Numb',          'Withdrawn'),
  ('Numb',          'Detached'),
  ('Numb',          'Checked-out'),
  ('Disenchanted',  'Ennui'),
  ('Disenchanted',  'Listless'),
  ('Disenchanted',  'Apathetic'),
  ('Disenchanted',  'World-weary'),
  ('Disenchanted',  'Restless'),
  ('Ashamed',       'Guilty'),
  ('Ashamed',       'Embarrassed'),
  ('Ashamed',       'Remorseful'),
  ('Burned out',    'Drained'),
  ('Burned out',    'Depleted'),
  ('Burned out',    'Exhausted'),
  ('Burned out',    'Resigned'),
  ('Anxious',       'Insecure'),
  ('Anxious',       'Worried'),
  ('Anxious',       'Nervous'),
  ('Anxious',       'Jittery'),
  ('Anxious',       'On edge'),
  ('Dread',         'Foreboding'),
  ('Dread',         'Apprehensive'),
  ('Dread',         'Bracing'),
  ('Dread',         'Uneasy'),
  ('Overwhelmed',   'Stressed'),
  ('Overwhelmed',   'Pressured'),
  ('Overwhelmed',   'Scattered'),
  ('Overwhelmed',   'Flooded'),
  ('Overwhelmed',   'Frozen'),
  ('Overwhelmed',   'Helpless'),
  ('Angry',         'Frustrated'),
  ('Angry',         'Irritated'),
  ('Angry',         'Resentful'),
  ('Angry',         'Bitter'),
  ('Angry',         'Mad'),
  ('Panicked',      'Terrified'),
  ('Panicked',      'Out of control'),
  ('Panicked',      'Alarmed'),
  ('Disgusted',     'Repulsed'),
  ('Disgusted',     'Appalled'),
  ('Disgusted',     'Revolted')
)
INSERT OR IGNORE INTO label (entry_type_id, name, parent_id)
SELECT et.id, v.child, pl.id
FROM entry_type et
JOIN v ON 1=1
JOIN label pl ON pl.entry_type_id = et.id AND pl.name = v.parent
WHERE et.name = 'Emotion';